using NJsonSchema;
using NJsonSchema.CodeGeneration.CSharp;
using System.Text.Json;

if (args.Length < 2)
{
    Console.WriteLine("Usage: SchemaCodeGenerator <schemas-directory> <output-file> [namespace]");
    Console.WriteLine("Example: SchemaCodeGenerator ./schemas ./Generated/Messages.cs MyNamespace.Messages");
    return 1;
}

var schemasDirectory = args[0];
var outputFile = args[1];
var targetNamespace = args.Length > 2 ? args[2] : "Generated";

if (!Directory.Exists(schemasDirectory))
{
    Console.WriteLine($"Error: Schemas directory not found: {schemasDirectory}");
    return 1;
}

var schemaFiles = Directory.GetFiles(schemasDirectory, "*.json", SearchOption.AllDirectories);

if (schemaFiles.Length == 0)
{
    Console.WriteLine($"No JSON schema files found in {schemasDirectory}");
    return 1;
}

Console.WriteLine($"Found {schemaFiles.Length} schema file(s)");

var topicsFile = Path.Combine(Directory.GetParent(schemasDirectory)?.FullName ?? schemasDirectory, "topics.json");
string? topicEnumCode = null;
if (File.Exists(topicsFile))
{
    Console.WriteLine($"Found topics file: {topicsFile}");
    try
    {
        var topicsJson = await File.ReadAllTextAsync(topicsFile);
        using var doc = JsonDocument.Parse(topicsJson);
        if (doc.RootElement.TryGetProperty("enum", out var enumArray) && enumArray.ValueKind == JsonValueKind.Array)
        {
            var enumValues = enumArray.EnumerateArray()
                .Select(e => $"    {e.GetString()}")
                .ToList();
            topicEnumCode = $"public enum Topic\n{{\n{string.Join(",\n", enumValues)},\n}}";
            Console.WriteLine($"Generated Topic enum with {enumValues.Count} values");
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Warning: Could not parse topics.json: {ex.Message}");
    }
}

var settings = new CSharpGeneratorSettings
{
    Namespace = targetNamespace,
    GenerateDataAnnotations = true,
    GenerateJsonMethods = true,
    GenerateNullableReferenceTypes = true,
    ClassStyle = CSharpClassStyle.Record,
    JsonLibrary = CSharpJsonLibrary.SystemTextJson,
    RequiredPropertiesMustBeDefined = true,
    DateType = "System.DateTimeOffset",
    DateTimeType = "System.DateTimeOffset"
};

var generatedCode = new List<string>
{
    "// <auto-generated>",
    "//     This code was generated by NJsonSchema from JSON schemas.",
    "//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.",
    "// </auto-generated>",
    "",
    "#nullable enable",
    "",
    $"namespace {targetNamespace};",
    ""
};

if (!string.IsNullOrEmpty(topicEnumCode))
{
    generatedCode.Add(topicEnumCode);
    generatedCode.Add("");
}

foreach (var schemaFile in schemaFiles)
{
    try
    {
        Console.WriteLine($"Processing: {schemaFile}");

        var schema = await JsonSchema.FromFileAsync(schemaFile);
        var generator = new CSharpGenerator(schema, settings);
        var code = generator.GenerateFile();

        var lines = code.Split('\n').ToList();

        var classStartIndex = lines.FindIndex(l =>
            l.TrimStart().StartsWith("[System.CodeDom.Compiler.GeneratedCode") ||
            l.TrimStart().StartsWith("public partial class") ||
            l.TrimStart().StartsWith("public class"));

        if (classStartIndex == -1)
            continue;

        var braceCount = 0;
        var classEndIndex = classStartIndex;
        var foundClassStart = false;

        for (var i = classStartIndex; i < lines.Count; i++)
        {
            var line = lines[i];
            if (line.Contains('{'))
            {
                braceCount += line.Count(c => c == '{');
                foundClassStart = true;
            }
            if (line.Contains('}'))
            {
                braceCount -= line.Count(c => c == '}');
            }

            if (foundClassStart && braceCount == 0)
            {
                classEndIndex = i;
                break;
            }
        }

        var classLines = lines.Skip(classStartIndex).Take(classEndIndex - classStartIndex + 1);
        generatedCode.AddRange(classLines);
        generatedCode.Add("");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error processing {schemaFile}: {ex.Message}");
    }
}

var outputDirectory = Path.GetDirectoryName(outputFile);
if (!string.IsNullOrEmpty(outputDirectory))
{
    Directory.CreateDirectory(outputDirectory);
}

await File.WriteAllTextAsync(outputFile, string.Join(Environment.NewLine, generatedCode));
Console.WriteLine($"Generated code written to: {outputFile}");

return 0;
